using Sunset.Parser.Visitors;

namespace Sunset.Markdown;

/// <summary>
/// Extension methods for accessing the pass data generated by a compiler pass.
/// </summary>
public static class MarkdownVisitorExtensions
{
    private const string PassDataKey = "MarkdownPrinter";

    public static string? GetResolvedSymbolExpression(this IVisitable dest)
    {
        return dest.GetPassData<MarkdownPassData>(PassDataKey).ResolvedSymbolExpression;
    }

    public static void SetResolvedSymbolExpression(this IVisitable dest, string symbolExpression)
    {
        dest.GetPassData<MarkdownPassData>(PassDataKey).ResolvedSymbolExpression = symbolExpression;
    }
}